
name: housing-bot
services:
    redis:
        image: redis:7-alpine
        restart: always
        volumes:
            - redis_data:/data
    app_bot:
        image: ghcr.io/angwltears/housingbot:latest
        restart: always
        depends_on:
            - redis
        environment:
            WGGESHUCHT_URL: ${WGGESHUCHT_URL}
            KLEINANZEIGEN_URL: ${KLEINANZEIGEN_URL}
            REDIS_URL: ${REDIS_URL}
            TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
            WOHNUNGSBOERSE_URL: ${WOHNUNGSBOERSE_URL}
volumes:
  redis_data:

